/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.codekeeper.gui;

import static com.codekeeper.utility.Helper.*;
import com.codekeeper.pojo.UserPojo;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.UIManager;

/**
 *
 * @author hardi
 */
public class Dashboard extends javax.swing.JFrame {

    /** Creates new form homeScreen */
    UserPojo user;
    public Dashboard() {
        UIManager.put( "TextComponent.arc", 10 );
        UIManager.put( "Button.arc", 40 );
        UIManager.put( "Component.arc", 10 );
        UIManager.put( "CheckBox.arc", 10 );
        UIManager.put( "ProgressBar.arc", 25 );
        FlatMacDarkLaf.setup();
        initComponents();
    }
    public Dashboard(UserPojo user){
        this();
        this.user = user;
        helper();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgUsr = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        txtUserMail = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        lblWeakPass = new javax.swing.JLabel();
        txtNoOfWeak = new javax.swing.JLabel();
        btnWeakBack = new javax.swing.JButton();
        lblSafePass = new javax.swing.JLabel();
        txtNoOfSafe = new javax.swing.JLabel();
        btnSafeBack = new javax.swing.JButton();
        btnHelp1 = new javax.swing.JButton();
        lblCompPass = new javax.swing.JLabel();
        txtNoOfComp = new javax.swing.JLabel();
        btnCompBack = new javax.swing.JButton();
        lblTotalPass = new javax.swing.JLabel();
        txtNoOfSaved = new javax.swing.JLabel();
        btnTotalBack = new javax.swing.JButton();
        userInfoBack = new javax.swing.JButton();
        txtStrongHelper = new javax.swing.JLabel();
        txtStrong = new javax.swing.JLabel();
        percentageStrong = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/codekeeper/icons/user1.png"))); // NOI18N
        imgUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgUsrMouseClicked(evt);
            }
        });
        jPanel1.add(imgUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 380, 90));

        txtUser.setFont(new java.awt.Font("Poppins", 1, 45)); // NOI18N
        txtUser.setForeground(new java.awt.Color(28, 69, 54));
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUser.setText("Rachit");
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 380, 50));

        txtUserMail.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtUserMail.setForeground(new java.awt.Color(28, 69, 54));
        txtUserMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUserMail.setText("himani21@gmail.com");
        jPanel1.add(txtUserMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 380, 30));

        btnLogout.setBackground(new java.awt.Color(207, 48, 63));
        btnLogout.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(229, 207, 207));
        btnLogout.setText("LOGOUT");
        btnLogout.setToolTipText("Logout?");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 290, 90));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/codekeeper/icons/4180bbb8-206d-45b0-bf21-81b9e745055c.jpg-output.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 470, 270));

        btnHelp.setBackground(new java.awt.Color(77, 77, 77));
        btnHelp.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(198, 226, 214));
        btnHelp.setText("<html><body>Got a question? We've got your back! Hit us up 👋</body></html>");
        btnHelp.setToolTipText("Help?");
        btnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp.setFocusable(false);
        btnHelp.setMargin(new java.awt.Insets(2, 35, 2, 14));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 290, 340));

        btnBack1.setBackground(new java.awt.Color(77, 77, 77));
        btnBack1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(198, 226, 214));
        btnBack1.setText("<html><body>Generate new password?</body></html>");
        btnBack1.setToolTipText("Go back to Home?");
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.setFocusable(false);
        btnBack1.setMargin(new java.awt.Insets(0, 35, 120, 35));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 470, 340));

        lblWeakPass.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblWeakPass.setForeground(new java.awt.Color(28, 69, 54));
        lblWeakPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeakPass.setText("Weak");
        jPanel1.add(lblWeakPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 180, 30));

        txtNoOfWeak.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        txtNoOfWeak.setForeground(new java.awt.Color(28, 69, 54));
        txtNoOfWeak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNoOfWeak.setText("79");
        jPanel1.add(txtNoOfWeak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 180, 60));

        btnWeakBack.setBackground(new java.awt.Color(198, 226, 214));
        btnWeakBack.setFocusable(false);
        btnWeakBack.setRequestFocusEnabled(false);
        jPanel1.add(btnWeakBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 180, 170));

        lblSafePass.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblSafePass.setForeground(new java.awt.Color(28, 69, 54));
        lblSafePass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSafePass.setText("Safe");
        jPanel1.add(lblSafePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 180, 30));

        txtNoOfSafe.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        txtNoOfSafe.setForeground(new java.awt.Color(28, 69, 54));
        txtNoOfSafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNoOfSafe.setText("43");
        jPanel1.add(txtNoOfSafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 180, 60));

        btnSafeBack.setBackground(new java.awt.Color(198, 226, 214));
        btnSafeBack.setFocusable(false);
        btnSafeBack.setRequestFocusEnabled(false);
        jPanel1.add(btnSafeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 180, 170));

        btnHelp1.setBackground(new java.awt.Color(28, 69, 54));
        btnHelp1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        btnHelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/codekeeper/icons/back.png"))); // NOI18N
        btnHelp1.setToolTipText("Go back to home?");
        btnHelp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp1.setFocusable(false);
        btnHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 70));

        lblCompPass.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblCompPass.setForeground(new java.awt.Color(28, 69, 54));
        lblCompPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompPass.setText("Compromised");
        jPanel1.add(lblCompPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 180, 30));

        txtNoOfComp.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        txtNoOfComp.setForeground(new java.awt.Color(28, 69, 54));
        txtNoOfComp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNoOfComp.setText("37");
        jPanel1.add(txtNoOfComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 180, 60));

        btnCompBack.setBackground(new java.awt.Color(198, 226, 214));
        btnCompBack.setFocusable(false);
        btnCompBack.setRequestFocusEnabled(false);
        jPanel1.add(btnCompBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 180, 170));

        lblTotalPass.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblTotalPass.setForeground(new java.awt.Color(28, 69, 54));
        lblTotalPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPass.setText("Total");
        jPanel1.add(lblTotalPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 180, 30));

        txtNoOfSaved.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        txtNoOfSaved.setForeground(new java.awt.Color(28, 69, 54));
        txtNoOfSaved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNoOfSaved.setText("12");
        jPanel1.add(txtNoOfSaved, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 180, 60));

        btnTotalBack.setBackground(new java.awt.Color(198, 226, 214));
        btnTotalBack.setFocusable(false);
        btnTotalBack.setRequestFocusEnabled(false);
        jPanel1.add(btnTotalBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 170));

        userInfoBack.setBackground(new java.awt.Color(154, 192, 167));
        userInfoBack.setFocusable(false);
        userInfoBack.setRequestFocusEnabled(false);
        userInfoBack.setRolloverEnabled(false);
        jPanel1.add(userInfoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 680));

        txtStrongHelper.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtStrongHelper.setForeground(new java.awt.Color(198, 226, 214));
        txtStrongHelper.setText("of your passwords are strong!");
        jPanel1.add(txtStrongHelper, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 310, 60));

        txtStrong.setFont(new java.awt.Font("Poppins Black", 0, 64)); // NOI18N
        txtStrong.setForeground(new java.awt.Color(198, 226, 214));
        txtStrong.setText("70%");
        jPanel1.add(txtStrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 310, 100));

        percentageStrong.setBackground(new java.awt.Color(0, 0, 0));
        percentageStrong.setForeground(new java.awt.Color(198, 226, 214));
        percentageStrong.setValue(70);
        jPanel1.add(percentageStrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 300, 10));

        jButton4.setBackground(new java.awt.Color(93, 93, 93));
        jButton4.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(198, 226, 214));
        jButton4.setText("EDIT PROFILE");
        jButton4.setFocusable(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 290, 150));

        jButton1.setBackground(new java.awt.Color(77, 77, 77));
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 350, 320));

        jButton2.setBackground(new java.awt.Color(77, 77, 77));
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 410, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1298, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imgUsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUsrMouseClicked
        
    }//GEN-LAST:event_imgUsrMouseClicked

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelp1ActionPerformed
        new HomeScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHelp1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        new GeneratePassword().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCompBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHelp1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSafeBack;
    private javax.swing.JButton btnTotalBack;
    private javax.swing.JButton btnWeakBack;
    private javax.swing.JLabel imgUsr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCompPass;
    private javax.swing.JLabel lblSafePass;
    private javax.swing.JLabel lblTotalPass;
    private javax.swing.JLabel lblWeakPass;
    private javax.swing.JProgressBar percentageStrong;
    private javax.swing.JLabel txtNoOfComp;
    private javax.swing.JLabel txtNoOfSafe;
    private javax.swing.JLabel txtNoOfSaved;
    private javax.swing.JLabel txtNoOfWeak;
    private javax.swing.JLabel txtStrong;
    private javax.swing.JLabel txtStrongHelper;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel txtUserMail;
    private javax.swing.JButton userInfoBack;
    // End of variables declaration//GEN-END:variables
    
    private void helper() {
        txtUser.setText(user.getName());
        imgUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageUrl(user.getUserImg()))));
        txtUserMail.setText(user.getEmail());
        btnHelp.setText(getSuggestions());
    }
}
